---
# Source: gitwebhookproxy/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: 0.2.32
    chart: "gitwebhookproxy-0.2.32"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: gitwebhookproxy
data:
    secret: ZHVtbXlzZWNyZXQ=
