---
# Source: gitwebhookproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
    version: 0.2.62
    chart: "gitwebhookproxy-0.2.62"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    expose: "true"
    
  name: gitwebhookproxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitwebhookproxy
    group: com.stakater.platform
    provider: stakater
