{{- if .Values.gitWebhookProxy.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.gitWebhookProxy.ingress.annotations }}
    {{- range . }}
    {{ .key }}: {{ .value }}
    {{- end }}
    {{- end }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
  namespace: {{ .Values.gitWebhookProxy.namespace }}
spec:
  rules:
  - host: {{ .Values.gitWebhookProxy.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}
          servicePort: {{ .Values.gitWebhookProxy.ingress.servicePort }}
  tls:
  - hosts:
    - {{ .Values.gitWebhookProxy.ingress.host }}
{{- end }}
