{{- if .Values.gitWebhookProxy.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.gitWebhookProxy.ingress.annotations }}
  annotations:
{{- range $key, $value := .Values.gitWebhookProxy.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
  namespace: {{ .Values.gitWebhookProxy.namespace }}
spec:
  rules:
  - host: {{ .Values.gitWebhookProxy.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.gitWebhookProxy.ingress.host }}
{{- end }}
