apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "name" . }}
{{- end }}
data:
    secret: {{ .Values.gitWebhookProxy.config.secret | b64enc }}