apiVersion: v1
kind: Service
metadata:
{{- if or .Values.gitWebhookProxy.service.annotations .Values.gitWebhookProxy.ingress.annotations }}
  annotations:
{{- end }}
{{- if .Values.gitWebhookProxy.ingress.annotations }}
    fabric8.io/ingress.annotations: |-
{{ toYaml .Values.gitWebhookProxy.ingress.annotations | indent 6 }}
{{- end }}
{{- if .Values.gitWebhookProxy.service.annotations }}
{{ toYaml .Values.gitWebhookProxy.service.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.gitWebhookProxy.service.labels }}
{{ toYaml .Values.gitWebhookProxy.service.labels | indent 4 }}
{{- end }}
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
{{ include "labels.selector" . | indent 4 }}