apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
data:
    secret: {{ .Values.gitWebhookProxy.config.secret | b64enc }}